### ISSUE TITLE
Ranking string sorted

### ISSUE THREAD

**Issue by mathias-goebel** [opaetzel/oik-backend#3]
[Ranking](https://dh-games.uni-goettingen.de/app/leaderboard) is sorted by strings and not numbers, e.g.

| 1 | opaetzel       | 61 |
|---|----------------|----|
| 2 | Martin Langner | 9  |
| 3 | mgoebel        | 0  |
| 34 | csporled       | 0  |
| 33 | Marta Kipke | 0 |

**Comment by opaetzel** [comment]
Is now sorted by rank.
